### ISSUE TITLE
Understand EC2 needs

### ISSUE THREAD

**Issue by coichedid** [numeract/aws-lambda-r#22]
Hello,

Very nice job!

I'm confused about EC2. Reading your documentation, I can't figure out why do I need a EC2 instance to build the package. Is it possible to do that locally? Is there some reason for that?

As I understand, after setting up all variables, I just need to run 01_main.sh script, right?

Best regards,
Clovis

**Comment by MikeBadescu** [comment]
Hi Clovis,

An AWS Lambda container does not have a regular Linux (e.g. Ubuntu) distribution but some stripped down variant that might not have all the packages we find in a regular distribution. Thus, to be sure that our package runs on AWS Lambda, we need to build it (i.e. install and compile) under the same configuration that is available on AWS Lambda. Hence, the EC2 instance that starts from a special AMI that contains the Lambda image. There are alternative where you can get the Lambda image in a docker container on your local machine, but they involve more moving parts - for this project we decided to stay within only AWS tools.

> As I understand, after setting up all variables, I just need to run 01_main.sh script, right?

Be sure to prepare your project as described in steps 2-5 (setting the variables is only one step). 

Script 01 will call script 03 which displays some error/info and ask for confirmation. You might want to run only script 03 and review each line to confirm your setup. 

Feel free to experiment, in the worst case scenario you will have to termianate certain EC2 instances and delete some configuration from the AWS web console.

**Comment by coichedid** [comment]
Very well!

I got it!

Thanks a lot for your help.

Clovis Chedid

Em qua, 25 de jul de 2018 às 13:11, Mike Badescu <notifications@github.com>
escreveu:
